remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  
title:            Brian McNitt
locale:           en_US
url:              https://bmcnitt.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Brian McNitt
  avatar: /assets/images/biopic.jpg
  bio: "I enjoy learning about statistics and software engineering."
  email: bmcnitt@su.suffolk.edu
  github: bmcnitt
  linkedin: brian-mcnitt


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]